/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TokenSaleEscrowInterface extends Interface {
    getFunction(nameOrSignature: "buyTokens" | "calculateCost" | "inventoryBalance" | "maxPerWallet" | "minPurchase" | "owner" | "pause" | "paused" | "paymentBalance" | "paymentToken" | "purchased" | "rate" | "renounceOwnership" | "saleToken" | "setMaxPerWallet" | "setMinPurchase" | "setRate" | "transferOwnership" | "unpause" | "withdrawPayments" | "withdrawUnsoldTokens"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MaxPerWalletUpdated" | "MinPurchaseUpdated" | "OwnershipTransferred" | "Paused" | "PaymentWithdrawn" | "RateUpdated" | "TokensPurchased" | "Unpaused" | "UnsoldTokensWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'buyTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateCost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'inventoryBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxPerWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'minPurchase', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'purchased', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'rate', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'saleToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMaxPerWallet', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMinPurchase', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawPayments', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawUnsoldTokens', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'buyTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inventoryBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxPerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minPurchase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchased', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'saleToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMaxPerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinPurchase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawPayments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawUnsoldTokens', data: BytesLike): Result;
  }

  
    export namespace MaxPerWalletUpdatedEvent {
      export type InputTuple = [oldMax: BigNumberish, newMax: BigNumberish];
      export type OutputTuple = [oldMax: bigint, newMax: bigint];
      export interface OutputObject {oldMax: bigint, newMax: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinPurchaseUpdatedEvent {
      export type InputTuple = [oldMin: BigNumberish, newMin: BigNumberish];
      export type OutputTuple = [oldMin: bigint, newMin: bigint];
      export interface OutputObject {oldMin: bigint, newMin: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RateUpdatedEvent {
      export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
      export type OutputTuple = [oldRate: bigint, newRate: bigint];
      export interface OutputObject {oldRate: bigint, newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, tsaleAmount: BigNumberish, paymentAmount: BigNumberish];
      export type OutputTuple = [buyer: string, tsaleAmount: bigint, paymentAmount: bigint];
      export interface OutputObject {buyer: string, tsaleAmount: bigint, paymentAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnsoldTokensWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TokenSaleEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): TokenSaleEscrow;
    waitForDeployment(): Promise<this>;

    interface: TokenSaleEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyTokens: TypedContractMethod<
      [tsaleAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    calculateCost: TypedContractMethod<
      [tsaleAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    inventoryBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxPerWallet: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minPurchase: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    paymentBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    purchased: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    rate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    saleToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setMaxPerWallet: TypedContractMethod<
      [newMax: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMinPurchase: TypedContractMethod<
      [newMin: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRate: TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawPayments: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawUnsoldTokens: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyTokens'): TypedContractMethod<
      [tsaleAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'calculateCost'): TypedContractMethod<
      [tsaleAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'inventoryBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxPerWallet'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minPurchase'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'paymentBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'purchased'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'saleToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setMaxPerWallet'): TypedContractMethod<
      [newMax: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinPurchase'): TypedContractMethod<
      [newMin: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRate'): TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawPayments'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawUnsoldTokens'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MaxPerWalletUpdated'): TypedContractEvent<MaxPerWalletUpdatedEvent.InputTuple, MaxPerWalletUpdatedEvent.OutputTuple, MaxPerWalletUpdatedEvent.OutputObject>;
getEvent(key: 'MinPurchaseUpdated'): TypedContractEvent<MinPurchaseUpdatedEvent.InputTuple, MinPurchaseUpdatedEvent.OutputTuple, MinPurchaseUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PaymentWithdrawn'): TypedContractEvent<PaymentWithdrawnEvent.InputTuple, PaymentWithdrawnEvent.OutputTuple, PaymentWithdrawnEvent.OutputObject>;
getEvent(key: 'RateUpdated'): TypedContractEvent<RateUpdatedEvent.InputTuple, RateUpdatedEvent.OutputTuple, RateUpdatedEvent.OutputObject>;
getEvent(key: 'TokensPurchased'): TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'UnsoldTokensWithdrawn'): TypedContractEvent<UnsoldTokensWithdrawnEvent.InputTuple, UnsoldTokensWithdrawnEvent.OutputTuple, UnsoldTokensWithdrawnEvent.OutputObject>;

    filters: {
      
      'MaxPerWalletUpdated(uint256,uint256)': TypedContractEvent<MaxPerWalletUpdatedEvent.InputTuple, MaxPerWalletUpdatedEvent.OutputTuple, MaxPerWalletUpdatedEvent.OutputObject>;
      MaxPerWalletUpdated: TypedContractEvent<MaxPerWalletUpdatedEvent.InputTuple, MaxPerWalletUpdatedEvent.OutputTuple, MaxPerWalletUpdatedEvent.OutputObject>;
    

      'MinPurchaseUpdated(uint256,uint256)': TypedContractEvent<MinPurchaseUpdatedEvent.InputTuple, MinPurchaseUpdatedEvent.OutputTuple, MinPurchaseUpdatedEvent.OutputObject>;
      MinPurchaseUpdated: TypedContractEvent<MinPurchaseUpdatedEvent.InputTuple, MinPurchaseUpdatedEvent.OutputTuple, MinPurchaseUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PaymentWithdrawn(address,uint256)': TypedContractEvent<PaymentWithdrawnEvent.InputTuple, PaymentWithdrawnEvent.OutputTuple, PaymentWithdrawnEvent.OutputObject>;
      PaymentWithdrawn: TypedContractEvent<PaymentWithdrawnEvent.InputTuple, PaymentWithdrawnEvent.OutputTuple, PaymentWithdrawnEvent.OutputObject>;
    

      'RateUpdated(uint256,uint256)': TypedContractEvent<RateUpdatedEvent.InputTuple, RateUpdatedEvent.OutputTuple, RateUpdatedEvent.OutputObject>;
      RateUpdated: TypedContractEvent<RateUpdatedEvent.InputTuple, RateUpdatedEvent.OutputTuple, RateUpdatedEvent.OutputObject>;
    

      'TokensPurchased(address,uint256,uint256)': TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
      TokensPurchased: TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'UnsoldTokensWithdrawn(address,uint256)': TypedContractEvent<UnsoldTokensWithdrawnEvent.InputTuple, UnsoldTokensWithdrawnEvent.OutputTuple, UnsoldTokensWithdrawnEvent.OutputObject>;
      UnsoldTokensWithdrawn: TypedContractEvent<UnsoldTokensWithdrawnEvent.InputTuple, UnsoldTokensWithdrawnEvent.OutputTuple, UnsoldTokensWithdrawnEvent.OutputObject>;
    
    };
  }